"""
Author: RawFish
Description: Constants and configuration values
If you would rather load these from other sources, feel free to ignore this file.
"""

VERSION = "1.0.0"

# Straight from stat_mapping.json

STAT_MAPPING = {
   "healthRegen": "Health Regen %",
   "manaRegen": "Mana Regen",
   "spellDamage": "Spell Damage %",
   "elementalSpellDamage": "Elemental Spell Damage %",
   "neutralSpellDamage": "Neutral Spell Damage %",
   "fireSpellDamage": "Fire Spell Damage %",
   "waterSpellDamage": "Water Spell Damage %",
   "airSpellDamage": "Air Spell Damage %",
   "thunderSpellDamage": "Thunder Spell Damage %",
   "earthSpellDamage": "Earth Spell Damage %",
   "mainAttackDamage": "Main Attack Damage %",
   "elementalMainAttackDamage": "Elemental Main Attack Damage %",
   "neutralMainAttackDamage": "Neutral Main Attack Damage %",
   "fireMainAttackDamage": "Fire Main Attack Damage %",
   "waterMainAttackDamage": "Water Main Attack Damage %",
   "airMainAttackDamage": "Air Main Attack Damage %",
   "thunderMainAttackDamage": "Thunder Main Attack Damage %",
   "earthMainAttackDamage": "Earth Main Attack Damage %",
   "lifeSteal": "Life Steal",
   "manaSteal": "Mana Steal",
   "xpBonus": "XP Bonus %",
   "lootBonus": "Loot Bonus %",
   "leveledXpBonus": "Leveled XP Bonus %",
   "leveledLootBonus": "Leveled Loot Bonus %",
   "reflection": "Reflection",
   "rawStrength": "Strength",
   "rawDexterity": "Dexterity",
   "rawIntelligence": "Intelligence",
   "rawDefence": "Defence",
   "rawAgility": "Agility",
   "thorns": "Thorns %",
   "poison": "Poison",
   "exploding": "Exploding %",
   "walkSpeed": "Walk Speed %",
   "rawAttackSpeed": "Attack Speed",
   "rawHealth": "Health",
   "soulPointRegen": "Soul Point Regen %",
   "stealing": "Stealing %",
   "healthRegenRaw": "Health Regen",
   "rawSpellDamage": "Spell Damage",
   "rawElementalSpellDamage": "Elemental Spell Damage",
   "rawNeutralSpellDamage": "Neutral Spell Damage",
   "rawFireSpellDamage": "Fire Spell Damage",
   "rawWaterSpellDamage": "Water Spell Damage",
   "rawAirSpellDamage": "Air Spell Damage",
   "rawThunderSpellDamage": "Thunder Spell Damage",
   "rawEarthSpellDamage": "Earth Spell Damage",
   "rawMainAttackDamage": "Main Attack Damage",
   "rawElementalMainAttackDamage": "Elemental Main Attack Damage",
   "rawNeutralMainAttackDamage": "Neutral Main Attack Damage",
   "rawFireMainAttackDamage": "Fire Main Attack Damage",
   "rawWaterMainAttackDamage": "Water Main Attack Damage ",
   "rawAirMainAttackDamage": "Air Main Attack Damage",
   "rawThunderMainAttackDamage": "Thunder Main Attack Damage",
   "rawEarthMainAttackDamage": "Earth Main Attack Damage",
   "damage": "Damage %",
   "neutralDamage": "Damage",
   "fireDamage": "Fire Damage",
   "waterDamage": "Water Damage",
   "airDamage": "Air Damage",
   "thunderDamage": "Thunder Damage",
   "earthDamage": "Earth Damage",
   "elementalDamage": "Elemental Damage %",
   "rawDamage": "Damage",
   "rawNeutralDamage": "Neutral Damage",
   "rawFireDamage": "Fire Damage",
   "rawWaterDamage": "Water Damage",
   "rawAirDamage": "Air Damage",
   "rawThunderDamage": "Thunder Damage",
   "rawEarthDamage": "Earth Damage",
   "rawElementalDamage": "Elemental Damage",
   "fireDefence": "Fire Defence %",
   "waterDefence": "Water Defence %",
   "airDefence": "Air Defence %",
   "thunderDefence": "Thunder Defence %",
   "earthDefence": "Earth Defence %",
   "elementalDefence": "Elemental Defence %",
   "1stSpellCost": "1st Spell Cost %",
   "raw1stSpellCost": "1st Spell Cost",
   "2ndSpellCost": "2nd Spell Cost %",
   "raw2ndSpellCost": "2nd Spell Cost",
   "3rdSpellCost": "3rd Spell Cost %",
   "raw3rdSpellCost": "3rd Spell Cost",
   "4thSpellCost": "4th Spell Cost %",
   "raw4thSpellCost": "4th Spell Cost",
   "sprint": "Sprint %",
   "sprintRegen": "Sprint Regen %",
   "jumpHeight": "Jump Height",
   "lootQuality": "Loot Quality %",
   "gatherXpBonus": "Gather XP Bonus %",
   "gatherSpeed": "Gather Speed %",
   "healingEfficiency": "Healing Efficiency %",
   "knockback": "Knockback %",
   "weakenEnemy": "Weaken Enemy %",
   "slowEnemy": "Slow Enemy %",
   "elementalDefence": "Elemental Defence %",
   "damageFromMobs": "Damage From Mobs %",
   "maxMana": "Max Mana %",
   "rawMaxMana": "Max Mana",
   "mainAttackRange": "Main Attack Range",
   "criticalDamageBonus": "Critical Damage Bonus"
}

TIER_COLORS = {
    "mythic": "#AA00AA",
    "fabled": "#FF5555",
    "legendary": "#55FFFF",
    "rare": "#FF55FF",
    "unique": "#c1c11f",
    "colaon": "#FFFFFF"
}

TIER_TRANSLATIONS = {
    "mythic": "Mythic",
    "fabled": "Fabled",
    "legendary": "Legendary",
    "rare": "Rare",
    "unique": "Unique",
}

SHINY_STATS = {
  {
    "id": 1,
    "key": "mobsKilled",
    "displayName": "Mobs Killed",
    "statUnit": "raw"
  },
  {
    "id": 2,
    "key": "raidsWon",
    "displayName": "Raids Won",
    "statUnit": "raw"
  },
  {
    "id": 3,
    "key": "chestsOpened",
    "displayName": "Chests Opened",
    "statUnit": "raw"
  },
  {
    "id": 4,
    "key": "warsWon",
    "displayName": "Wars Won",
    "statUnit": "raw"
  },
  {
    "id": 5,
    "key": "playersKilled",
    "displayName": "Players Killed",
    "statUnit": "raw"
  },
  {
    "id": 6,
    "key": "dungeonsWon",
    "displayName": "Dungeons Won",
    "statUnit": "raw"
  },
  {
    "id": 7,
    "key": "deaths",
    "displayName": "Deaths",
    "statUnit": "raw"
  },
  {
    "id": 8,
    "key": "lootrunsCompleted",
    "displayName": "Lootruns Completed",
    "statUnit": "raw"
  }
}

# from Wynntils static storage 
ID_MAP = {
  "1stSpellCost": 0,
  "2ndSpellCost": 1,
  "3rdSpellCost": 2,
  "4thSpellCost": 3,
  "airDamage": 4,
  "airDefence": 5,
  "airMainAttackDamage": 6,
  "airSpellDamage": 7,
  "damageFromMobs": 8,
  "earthDamage": 9,
  "earthDefence": 10,
  "earthMainAttackDamage": 11,
  "earthSpellDamage": 12,
  "elementalDamage": 13,
  "elementalDefence": 14,
  "elementalDefense": 15,
  "elementalSpellDamage": 16,
  "exploding": 17,
  "fireDamage": 18,
  "fireDefence": 19,
  "fireSpellDamage": 20,
  "gatherSpeed": 21,
  "gatherXpBonus": 22,
  "healingEfficiency": 23,
  "healthRegen": 24,
  "healthRegenRaw": 25,
  "jumpHeight": 26,
  "knockback": 27,
  "leveledLootBonus": 28,
  "leveledXpBonus": 29,
  "lifeSteal": 30,
  "lootBonus": 31,
  "lootQuality": 32,
  "mainAttackDamage": 33,
  "manaRegen": 34,
  "manaSteal": 35,
  "poison": 36,
  "raw1stSpellCost": 37,
  "raw2ndSpellCost": 38,
  "raw3rdSpellCost": 39,
  "raw4thSpellCost": 40,
  "rawAgility": 41,
  "rawAirDamage": 42,
  "rawAirMainAttackDamage": 43,
  "rawAirSpellDamage": 44,
  "rawAttackSpeed": 45,
  "rawDefence": 46,
  "rawDexterity": 47,
  "rawEarthDamage": 48,
  "rawEarthSpellDamage": 49,
  "rawElementalDamage": 50,
  "rawElementalMainAttackDamage": 51,
  "rawElementalSpellDamage": 52,
  "rawFireDamage": 53,
  "rawFireMainAttackDamage": 54,
  "rawFireSpellDamage": 55,
  "rawHealth": 56,
  "rawIntelligence": 57,
  "rawMainAttackDamage": 58,
  "rawNeutralDamage": 59,
  "rawNeutralSpellDamage": 60,
  "rawSpellDamage": 61,
  "rawStrength": 62,
  "rawThunderDamage": 63,
  "rawThunderMainAttackDamage": 64,
  "rawThunderSpellDamage": 65,
  "rawWaterDamage": 66,
  "rawWaterMainAttackDamage": 67,
  "rawWaterSpellDamage": 68,
  "reflection": 69,
  "slowEnemy": 70,
  "soulPointRegen": 71,
  "spellDamage": 72,
  "sprint": 73,
  "sprintRegen": 74,
  "stealing": 75,
  "thorns": 76,
  "thunderDamage": 77,
  "thunderDefence": 78,
  "thunderMainAttackDamage": 79,
  "thunderSpellDamage": 80,
  "walkSpeed": 81,
  "waterDamage": 82,
  "waterDefence": 83,
  "waterSpellDamage": 84,
  "weakenEnemy": 85,
  "xpBonus": 86,
  "healing": 87,
  "rawEarthMainAttackDamage": 88,
  "agility": 89,
  "baseAirDamage": 90,
  "baseAirDefence": 91,
  "baseDamage": 92,
  "baseEarthDamage": 93,
  "baseEarthDefence": 94,
  "baseFireDamage": 95,
  "baseFireDefence": 96,
  "baseHealth": 97,
  "baseThunderDamage": 98,
  "baseThunderDefence": 99,
  "baseWaterDamage": 100,
  "baseWaterDefence": 101,
  "damage": 102,
  "defence": 103,
  "dexterity": 104,
  "elementalMainAttackDamage": 105,
  "fireMainAttackDamage": 106,
  "intelligence": 107,
  "neutralDamage": 108,
  "neutralMainAttackDamage": 109,
  "rawDamage": 110,
  "rawNeutralMainAttackDamage": 111,
  "strength": 112,
  "fireSpellDamageBonus": 113,
  "thunderMeleeDamageBonusRaw": 114,
  "maxMana": 115,
  "neutralSpellDamage": 116,
  "rawMaxMana": 117,
  "mainAttackRange": 118,
  "criticalDamageBonus": 119
}