# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/common/components.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/common/components.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wynnsource.common import enums_pb2 as wynnsource_dot_common_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"wynnsource/common/components.proto\x12\x11wynnsource.common\x1a\x1dwynnsource/common/enums.proto\"T\n\x0b\x44\x61mageRange\x12+\n\x07\x65lement\x18\x01 \x01(\x0e\x32\x1a.wynnsource.common.Element\x12\x0b\n\x03min\x18\x02 \x01(\x05\x12\x0b\n\x03max\x18\x03 \x01(\x05\"&\n\nLevelRange\x12\x0b\n\x03min\x18\x01 \x01(\x05\x12\x0b\n\x03max\x18\x02 \x01(\x05\"E\n\x07\x44\x65\x66\x65nse\x12+\n\x07\x65lement\x18\x01 \x01(\x0e\x32\x1a.wynnsource.common.Element\x12\r\n\x05value\x18\x02 \x01(\x05\"@\n\x0eIdentification\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08\x62\x61se_val\x18\x02 \x01(\x05\x12\x10\n\x08roll_10k\x18\x03 \x01(\x05\"I\n\x15\x43raftedIdentification\x12\n\n\x02id\x18\x01 \x01(\r\x12\x13\n\x0b\x63urrent_val\x18\x02 \x01(\x05\x12\x0f\n\x07max_val\x18\x03 \x01(\x05\"=\n\rCraftedEffect\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07min_val\x18\x02 \x01(\x05\x12\x0f\n\x07max_val\x18\x03 \x01(\x05\"\xbf\x01\n\x0cRequirements\x12\r\n\x05level\x18\x01 \x01(\x05\x12/\n\tclass_req\x18\x02 \x01(\x0e\x32\x1c.wynnsource.common.ClassType\x12\x14\n\x0cstrength_req\x18\x03 \x01(\x05\x12\x15\n\rdexterity_req\x18\x04 \x01(\x05\x12\x18\n\x10intelligence_req\x18\x05 \x01(\x05\x12\x13\n\x0b\x64\x65\x66\x65nse_req\x18\x06 \x01(\x05\x12\x13\n\x0b\x61gility_req\x18\x07 \x01(\x05\"D\n\x06Powder\x12+\n\x07\x65lement\x18\x01 \x01(\x0e\x32\x1a.wynnsource.common.Element\x12\r\n\x05level\x18\x02 \x01(\x05\">\n\nPowderSlot\x12\x30\n\x06powder\x18\x01 \x01(\x0b\x32\x19.wynnsource.common.PowderB\x05\xaa\x01\x02\x08\x01\"0\n\x05Shiny\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x0c\n\x04roll\x18\x03 \x01(\x05\"+\n\x0b\x43raftedMeta\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04lore\x18\x02 \x01(\t\"*\n\nDurability\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x05\x12\x0b\n\x03max\x18\x02 \x01(\x05\x42\"\n fyw.fyi.wynnsource.schema.commonb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.common.components_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n fyw.fyi.wynnsource.schema.common'
  _globals['_POWDERSLOT'].fields_by_name['powder']._loaded_options = None
  _globals['_POWDERSLOT'].fields_by_name['powder']._serialized_options = b'\252\001\002\010\001'
  _globals['_DAMAGERANGE']._serialized_start=88
  _globals['_DAMAGERANGE']._serialized_end=172
  _globals['_LEVELRANGE']._serialized_start=174
  _globals['_LEVELRANGE']._serialized_end=212
  _globals['_DEFENSE']._serialized_start=214
  _globals['_DEFENSE']._serialized_end=283
  _globals['_IDENTIFICATION']._serialized_start=285
  _globals['_IDENTIFICATION']._serialized_end=349
  _globals['_CRAFTEDIDENTIFICATION']._serialized_start=351
  _globals['_CRAFTEDIDENTIFICATION']._serialized_end=424
  _globals['_CRAFTEDEFFECT']._serialized_start=426
  _globals['_CRAFTEDEFFECT']._serialized_end=487
  _globals['_REQUIREMENTS']._serialized_start=490
  _globals['_REQUIREMENTS']._serialized_end=681
  _globals['_POWDER']._serialized_start=683
  _globals['_POWDER']._serialized_end=751
  _globals['_POWDERSLOT']._serialized_start=753
  _globals['_POWDERSLOT']._serialized_end=815
  _globals['_SHINY']._serialized_start=817
  _globals['_SHINY']._serialized_end=865
  _globals['_CRAFTEDMETA']._serialized_start=867
  _globals['_CRAFTEDMETA']._serialized_end=910
  _globals['_DURABILITY']._serialized_start=912
  _globals['_DURABILITY']._serialized_end=954
# @@protoc_insertion_point(module_scope)
