# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/common/enums.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/common/enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dwynnsource/common/enums.proto\x12\x11wynnsource.common*\xc8\x01\n\x06Rarity\x12\x16\n\x12RARITY_UNSPECIFIED\x10\x00\x12\x0f\n\x0bRARITY_NONE\x10\x01\x12\x11\n\rRARITY_COMMON\x10\x02\x12\x11\n\rRARITY_UNIQUE\x10\x03\x12\x0f\n\x0bRARITY_RARE\x10\x04\x12\x14\n\x10RARITY_LEGENDARY\x10\x05\x12\x11\n\rRARITY_FABLED\x10\x06\x12\x11\n\rRARITY_MYTHIC\x10\x07\x12\x0e\n\nRARITY_SET\x10\x08\x12\x12\n\x0eRARITY_CRAFTED\x10\t*\x95\x01\n\x07\x45lement\x12\x17\n\x13\x45LEMENT_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x45LEMENT_NEUTRAL\x10\x01\x12\x11\n\rELEMENT_EARTH\x10\x02\x12\x13\n\x0f\x45LEMENT_THUNDER\x10\x03\x12\x11\n\rELEMENT_WATER\x10\x04\x12\x10\n\x0c\x45LEMENT_FIRE\x10\x05\x12\x0f\n\x0b\x45LEMENT_AIR\x10\x06*\xaf\x01\n\tClassType\x12\x1a\n\x16\x43LASS_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x43LASS_TYPE_ANY\x10\x01\x12\x16\n\x12\x43LASS_TYPE_WARRIOR\x10\x02\x12\x13\n\x0f\x43LASS_TYPE_MAGE\x10\x03\x12\x15\n\x11\x43LASS_TYPE_ARCHER\x10\x04\x12\x17\n\x13\x43LASS_TYPE_ASSASSIN\x10\x05\x12\x15\n\x11\x43LASS_TYPE_SHAMAN\x10\x06*\xfb\x01\n\nProfession\x12\x1a\n\x16PROFESSION_UNSPECIFIED\x10\x00\x12\x18\n\x14PROFESSION_ARMOURING\x10\x01\x12\x18\n\x14PROFESSION_TAILORING\x10\x02\x12\x17\n\x13PROFESSION_JEWELING\x10\x03\x12\x1d\n\x19PROFESSION_WEAPONSMITHING\x10\x04\x12\x1a\n\x16PROFESSION_WOODWORKING\x10\x05\x12\x18\n\x14PROFESSION_ALCHEMISM\x10\x06\x12\x17\n\x13PROFESSION_SCRIBING\x10\x07\x12\x16\n\x12PROFESSION_COOKING\x10\x08*U\n\x04Raid\x12\x14\n\x10RAID_UNSPECIFIED\x10\x00\x12\r\n\tRAID_NOTG\x10\x01\x12\x0c\n\x08RAID_NOL\x10\x02\x12\x0c\n\x08RAID_TCC\x10\x03\x12\x0c\n\x08RAID_TNA\x10\x04*\x99\x01\n\x10IngredientRarity\x12!\n\x1dINGREDIENT_RARITY_UNSPECIFIED\x10\x00\x12\x17\n\x13INGREDIENT_RARITY_0\x10\x01\x12\x17\n\x13INGREDIENT_RARITY_1\x10\x02\x12\x17\n\x13INGREDIENT_RARITY_2\x10\x03\x12\x17\n\x13INGREDIENT_RARITY_3\x10\x04\x42\"\n fyw.fyi.wynnsource.schema.commonb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.common.enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n fyw.fyi.wynnsource.schema.common'
  _globals['_RARITY']._serialized_start=53
  _globals['_RARITY']._serialized_end=253
  _globals['_ELEMENT']._serialized_start=256
  _globals['_ELEMENT']._serialized_end=405
  _globals['_CLASSTYPE']._serialized_start=408
  _globals['_CLASSTYPE']._serialized_end=583
  _globals['_PROFESSION']._serialized_start=586
  _globals['_PROFESSION']._serialized_end=837
  _globals['_RAID']._serialized_start=839
  _globals['_RAID']._serialized_end=924
  _globals['_INGREDIENTRARITY']._serialized_start=927
  _globals['_INGREDIENTRARITY']._serialized_end=1080
# @@protoc_insertion_point(module_scope)
