# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/item/corkian_modifier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/item/corkian_modifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&wynnsource/item/corkian_modifier.proto\x12\x0fwynnsource.item\"E\n\x0f\x43orkianModifier\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.wynnsource.item.CorkianModifierType*\xab\x01\n\x13\x43orkianModifierType\x12%\n!CORKIAN_MODIFIER_TYPE_UNSPECIFIED\x10\x00\x12#\n\x1f\x43ORKIAN_MODIFIER_TYPE_AMPLIFIER\x10\x01\x12#\n\x1f\x43ORKIAN_MODIFIER_TYPE_SIMULATOR\x10\x02\x12#\n\x1f\x43ORKIAN_MODIFIER_TYPE_INSULATOR\x10\x03\x42 \n\x1e\x66yw.fyi.wynnsource.schema.itemb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.item.corkian_modifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036fyw.fyi.wynnsource.schema.item'
  _globals['_CORKIANMODIFIERTYPE']._serialized_start=131
  _globals['_CORKIANMODIFIERTYPE']._serialized_end=302
  _globals['_CORKIANMODIFIER']._serialized_start=59
  _globals['_CORKIANMODIFIER']._serialized_end=128
# @@protoc_insertion_point(module_scope)
