# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/item/crafter_bag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/item/crafter_bag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wynnsource.common import enums_pb2 as wynnsource_dot_common_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!wynnsource/item/crafter_bag.proto\x12\x0fwynnsource.item\x1a\x1dwynnsource/common/enums.proto\"m\n\nCrafterBag\x12\x33\n\x06rarity\x18\x01 \x01(\x0e\x32#.wynnsource.common.IngredientRarity\x12*\n\tdrop_raid\x18\x02 \x01(\x0e\x32\x17.wynnsource.common.RaidB \n\x1e\x66yw.fyi.wynnsource.schema.itemb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.item.crafter_bag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036fyw.fyi.wynnsource.schema.item'
  _globals['_CRAFTERBAG']._serialized_start=85
  _globals['_CRAFTERBAG']._serialized_end=194
# @@protoc_insertion_point(module_scope)
