# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/item/emerald.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/item/emerald.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dwynnsource/item/emerald.proto\x12\x0fwynnsource.item\"5\n\x07\x45merald\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.wynnsource.item.EmeraldType*v\n\x0b\x45meraldType\x12\x1c\n\x18\x45MERALD_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14\x45MERALD_TYPE_EMERALD\x10\x01\x12\x16\n\x12\x45MERALD_TYPE_BLOCK\x10\x02\x12\x17\n\x13\x45MERALD_TYPE_LIQUID\x10\x03\x42 \n\x1e\x66yw.fyi.wynnsource.schema.itemb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.item.emerald_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036fyw.fyi.wynnsource.schema.item'
  _globals['_EMERALDTYPE']._serialized_start=105
  _globals['_EMERALDTYPE']._serialized_end=223
  _globals['_EMERALD']._serialized_start=50
  _globals['_EMERALD']._serialized_end=103
# @@protoc_insertion_point(module_scope)
