# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/item/ingredient.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/item/ingredient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wynnsource.common import components_pb2 as wynnsource_dot_common_dot_components__pb2
from wynnsource.common import enums_pb2 as wynnsource_dot_common_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n wynnsource/item/ingredient.proto\x12\x0fwynnsource.item\x1a\"wynnsource/common/components.proto\x1a\x1dwynnsource/common/enums.proto\"#\n\x0bModifierPos\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"D\n\x08Modifier\x12)\n\x03pos\x18\x01 \x01(\x0b\x32\x1c.wynnsource.item.ModifierPos\x12\r\n\x05value\x18\x02 \x01(\x05\"~\n\x0bReqModifier\x12\x14\n\x0cstrength_req\x18\x03 \x01(\x05\x12\x15\n\rdexterity_req\x18\x04 \x01(\x05\x12\x18\n\x10intelligence_req\x18\x05 \x01(\x05\x12\x13\n\x0b\x64\x65\x66\x65nse_req\x18\x06 \x01(\x05\x12\x13\n\x0b\x61gility_req\x18\x07 \x01(\x05\"\xc1\x02\n\nIngredient\x12\x12\n\ndurability\x18\x01 \x01(\x05\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x0f\n\x07\x63harges\x18\x03 \x01(\x05\x12\x33\n\x06rarity\x18\x04 \x01(\x0e\x32#.wynnsource.common.IngredientRarity\x12\x31\n\x07\x65\x66\x66\x65\x63ts\x18\x05 \x03(\x0b\x32 .wynnsource.common.CraftedEffect\x12\x32\n\x0bprofessions\x18\x06 \x03(\x0e\x32\x1d.wynnsource.common.Profession\x12,\n\tmodifiers\x18\x07 \x03(\x0b\x32\x19.wynnsource.item.Modifier\x12\x32\n\x0creq_modifier\x18\x08 \x01(\x0b\x32\x1c.wynnsource.item.ReqModifierB \n\x1e\x66yw.fyi.wynnsource.schema.itemb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.item.ingredient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036fyw.fyi.wynnsource.schema.item'
  _globals['_MODIFIERPOS']._serialized_start=120
  _globals['_MODIFIERPOS']._serialized_end=155
  _globals['_MODIFIER']._serialized_start=157
  _globals['_MODIFIER']._serialized_end=225
  _globals['_REQMODIFIER']._serialized_start=227
  _globals['_REQMODIFIER']._serialized_end=353
  _globals['_INGREDIENT']._serialized_start=356
  _globals['_INGREDIENT']._serialized_end=677
# @@protoc_insertion_point(module_scope)
