# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/item/material.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/item/material.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ewynnsource/item/material.proto\x12\x0fwynnsource.item\"7\n\x08Material\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.wynnsource.item.MaterialType*\xf0\x01\n\x0cMaterialType\x12\x1d\n\x19MATERIAL_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13MATERIAL_TYPE_INGOT\x10\x01\x12\x15\n\x11MATERIAL_TYPE_GEM\x10\x02\x12\x16\n\x12MATERIAL_TYPE_WOOD\x10\x03\x12\x17\n\x13MATERIAL_TYPE_PAPER\x10\x04\x12\x18\n\x14MATERIAL_TYPE_STRING\x10\x05\x12\x17\n\x13MATERIAL_TYPE_GRAIN\x10\x06\x12\x15\n\x11MATERIAL_TYPE_OIL\x10\x07\x12\x16\n\x12MATERIAL_TYPE_MEAT\x10\x08\x42 \n\x1e\x66yw.fyi.wynnsource.schema.itemb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.item.material_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036fyw.fyi.wynnsource.schema.item'
  _globals['_MATERIALTYPE']._serialized_start=109
  _globals['_MATERIALTYPE']._serialized_end=349
  _globals['_MATERIAL']._serialized_start=51
  _globals['_MATERIAL']._serialized_end=106
# @@protoc_insertion_point(module_scope)
