# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/item/misc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/item/misc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awynnsource/item/misc.proto\x12\x0fwynnsource.item\"\x06\n\x04Rune\"\x0c\n\nDungeonKey\"\t\n\x07Trinket\"\x10\n\x0eTeleportScroll\"\x0e\n\x0c\x45meraldPouch\"\x07\n\x05NamedB \n\x1e\x66yw.fyi.wynnsource.schema.itemb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.item.misc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036fyw.fyi.wynnsource.schema.item'
  _globals['_RUNE']._serialized_start=47
  _globals['_RUNE']._serialized_end=53
  _globals['_DUNGEONKEY']._serialized_start=55
  _globals['_DUNGEONKEY']._serialized_end=67
  _globals['_TRINKET']._serialized_start=69
  _globals['_TRINKET']._serialized_end=78
  _globals['_TELEPORTSCROLL']._serialized_start=80
  _globals['_TELEPORTSCROLL']._serialized_end=96
  _globals['_EMERALDPOUCH']._serialized_start=98
  _globals['_EMERALDPOUCH']._serialized_end=112
  _globals['_NAMED']._serialized_start=114
  _globals['_NAMED']._serialized_end=121
# @@protoc_insertion_point(module_scope)
