# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/item/mount.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/item/mount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bwynnsource/item/mount.proto\x12\x0fwynnsource.item\"C\n\x07MountXp\x12\x12\n\ncurrent_xp\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrent_lvl\x18\x02 \x01(\x05\x12\x0f\n\x07max_lvl\x18\x03 \x01(\x05\"]\n\x05Mount\x12.\n\nmount_type\x18\x01 \x01(\x0e\x32\x1a.wynnsource.item.MountType\x12$\n\x02xp\x18\x02 \x01(\x0b\x32\x18.wynnsource.item.MountXp*l\n\tMountType\x12\x1a\n\x16MOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10MOUNT_TYPE_HORSE\x10\x01\x12\x15\n\x11MOUNT_TYPE_WYVERN\x10\x02\x12\x16\n\x12MOUNT_TYPE_ADASAUR\x10\x03\x42 \n\x1e\x66yw.fyi.wynnsource.schema.itemb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.item.mount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036fyw.fyi.wynnsource.schema.item'
  _globals['_MOUNTTYPE']._serialized_start=212
  _globals['_MOUNTTYPE']._serialized_end=320
  _globals['_MOUNTXP']._serialized_start=48
  _globals['_MOUNTXP']._serialized_end=115
  _globals['_MOUNT']._serialized_start=117
  _globals['_MOUNT']._serialized_end=210
# @@protoc_insertion_point(module_scope)
