# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wynnsource/item/tome.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wynnsource/item/tome.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wynnsource.common import components_pb2 as wynnsource_dot_common_dot_components__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awynnsource/item/tome.proto\x12\x0fwynnsource.item\x1a\"wynnsource/common/components.proto\"k\n\x04Tome\x12\'\n\x04slot\x18\x01 \x01(\x0e\x32\x19.wynnsource.item.TomeSlot\x12:\n\x0fidentifications\x18\x02 \x03(\x0b\x32!.wynnsource.common.Identification*\xc7\x01\n\x08TomeSlot\x12\x19\n\x15TOME_SLOT_UNSPECIFIED\x10\x00\x12\x14\n\x10TOME_SLOT_ARMOUR\x10\x01\x12\x14\n\x10TOME_SLOT_WEAPON\x10\x02\x12\x17\n\x13TOME_SLOT_EXPERTISE\x10\x03\x12\x16\n\x12TOME_SLOT_MARATHON\x10\x04\x12\x17\n\x13TOME_SLOT_MYSTICISM\x10\x05\x12\x15\n\x11TOME_SLOT_LOOTRUN\x10\x06\x12\x13\n\x0fTOME_SLOT_GUILD\x10\x07\x42 \n\x1e\x66yw.fyi.wynnsource.schema.itemb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wynnsource.item.tome_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036fyw.fyi.wynnsource.schema.item'
  _globals['_TOMESLOT']._serialized_start=193
  _globals['_TOMESLOT']._serialized_end=392
  _globals['_TOME']._serialized_start=83
  _globals['_TOME']._serialized_end=190
# @@protoc_insertion_point(module_scope)
